# Generated by Django 5.2.6 on 2025-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_useradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='image',
            field=models.ImageField(default=0, upload_to='image/'),
        ),
    ]
